version: '3.7'
services:
    fundamentals:
        container_name: 03-fundamentals-app
        build:
            context: .
            dockerfile: .docker/node.dockerfile
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
          - .node_logs:/root/.npm/
        ports:
          - "8081:8000"
